import { ToolDefinition, ToolHandlerResult, EngineContext } from './types.js';

export const definition: ToolDefinition = {
  name: 'create_request',
  description: "Adds a request to an existing collection. When to use: for each endpoint found while reading route handler source - infer method, URL, headers, and body shape from the handler, TypeScript types, Zod schemas, and validation middleware are the most reliable sources. Preferred pattern: call create_collection first if the collection doesn't exist yet, then one create_request call per endpoint. CRITICAL: Use {{baseUrl}} or {{token}} for environment variables if you detect them in the codebase, rather than hardcoding values like http://localhost:3000. Prefer placing query parameters in the `params` object rather than hardcoding them into the `url`. For multipart/form-data requests set body.type to 'multipart' and provide body.parts. File parts use filePath (relative to the project root - the file must exist at run time). Text parts use value. For gRPC requests: set type to 'grpc', set url to the server address (e.g. 'localhost:50051'), and provide a grpc block with protoFile (relative to .reqly/protos/), service (e.g. 'helloworld.Greeter'), method (e.g. 'SayHello'), and message. Proto files must be placed in .reqly/protos/. Use headers for gRPC Metadata. Auth profiles inject automatically. For complex scripts (multi-line, no JSON escaping headache): write the .js file first with write_file (e.g. '.reqly/collections/auth/scripts/login-post.js'), then reference it via postScriptFile: 'scripts/login-post.js' - the engine reads the file at run time so edits are instant without touching the YAML.",
  inputSchema: {
    type: 'object',
    properties: {
      collectionName: { type: 'string' },
      request: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          name: { type: 'string' },
          method: { type: 'string' },
          url: { type: 'string' },
          headers: { type: 'object' },
          body: {
            oneOf: [
              { type: 'string', description: 'Raw body string (use for raw/plain-text bodies)' },
              {
                type: 'object',
                description: 'JSON object body - serialised as application/json automatically',
              },
              {
                type: 'object',
                description: "Multipart body. Set type to 'multipart' and provide parts. Text parts: { type: 'text', name, value }. File parts: { type: 'file', name, filePath, contentType? } where filePath is relative to the project root and the file must exist at run time.",
                properties: {
                  type: { type: 'string', enum: ['multipart'] },
                  parts: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        name: { type: 'string' },
                        type: { type: 'string', enum: ['text', 'file'] },
                        value: { type: 'string', description: 'Used for text parts' },
                        filePath: { type: 'string', description: 'Path relative to project root, used for file parts' },
                        contentType: { type: 'string', description: 'MIME type override for file parts (e.g. image/jpeg). Auto-detected if omitted.' },
                      },
                      required: ['name', 'type'],
                    },
                  },
                },
                required: ['type', 'parts'],
              },
            ],
          },
          params: { type: 'object' },
          disabledParams: {
            type: 'array',
            items: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' } } },
          },
          disabledHeaders: {
            type: 'array',
            items: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' } } },
          },
          authProfileId: { type: 'string' },
          environmentId: { type: 'string' },
          type: { type: 'string', enum: ['rest', 'graphql', 'grpc'] },
          graphql: {
            type: 'object',
            properties: {
              query: { type: 'string' },
              queryFile: { type: 'string', description: 'Path to a .graphql file relative to the project root. If set, query is ignored.' },
              variables: { type: 'object' },
              operationName: { type: 'string' }
            }
          },
          grpc: {
            type: 'object',
            description: "gRPC-specific config. Required when type is 'grpc'. Proto files must be placed in .reqly/protos/ (supports subdirectories and cross-file imports). Use `url` on the request for the server address (e.g. 'localhost:50051'). Use `headers` for gRPC Metadata - auth profiles also inject automatically into Metadata. message scaffold is auto-generated by create_request when service and method are provided (T-166).",
            properties: {
              protoFile: { type: 'string', description: 'Path to the .proto file relative to .reqly/protos/, e.g. "helloworld.proto" or "api/user.proto"' },
              service: { type: 'string', description: 'Fully-qualified service name, e.g. "helloworld.Greeter"' },
              method: { type: 'string', description: 'Method name on the service, e.g. "SayHello"' },
              message: { type: 'object', description: 'JSON message body to send. Leave empty for auto-scaffold.' },
              insecure: { type: 'boolean', description: 'Use insecure (plaintext) channel. Default: true.' },
              streaming: { type: 'string', enum: ['server', 'client', 'bidirectional'], description: 'Streaming mode (T-168). Omit for unary.' },
              streamTimeout: { type: 'number', description: 'Max seconds to buffer for streaming modes (default: 5)' },
              messages: { type: 'array', items: { type: 'object' }, description: 'For client/bidirectional streaming: array of messages to send' }
            },
            required: ['protoFile', 'service', 'method']
          },
          assertions: {
            type: 'array',
            description: "Optional assertions run automatically after every execution of this request. Each object: { field, operator, value, path? }. IMPORTANT: use 'field' (not 'type') to name what to check. field: 'status' | 'body' | 'latency'. operator: 'eq' | 'neq' | 'contains' | 'lt' | 'gt'. path: dot-notation into JSON body (body only). Examples: { field: 'status', operator: 'eq', value: 200 } | { field: 'body', path: 'user.active', operator: 'eq', value: true } | { field: 'latency', operator: 'lt', value: 1000 }",
            items: {
              type: 'object',
              properties: {
                field: { type: 'string', enum: ['status', 'body', 'latency'] },
                path: { type: 'string', description: "body only: dot-notation path, e.g. 'data.id'" },
                operator: { type: 'string', enum: ['eq', 'neq', 'contains', 'lt', 'gt'] },
                value: { description: 'Expected value (string, number, or boolean)' },
              },
              required: ['field', 'operator', 'value'],
            },
          },
          preScript: { type: 'string', description: 'JavaScript executed before the request fires. Has access to env (read/write) and request (read-only). Wins over preScriptFile if both set.' },
          postScript: { type: 'string', description: 'JavaScript executed after the response is received. Has access to env (read/write), request, and response (read-only). Wins over postScriptFile if both set.' },
          preScriptFile: { type: 'string', description: 'Path to a .js file relative to the collection folder (e.g. "scripts/pre.js"). Engine reads the file at run time - edits are picked up without touching the YAML. Preferred agent pattern for complex scripts: write_file(".reqly/collections/<name>/scripts/pre.js", script) then set preScriptFile: "scripts/pre.js". No ../path-traversal allowed.' },
          postScriptFile: { type: 'string', description: 'Path to a .js file relative to the collection folder (e.g. "scripts/post.js"). Engine reads the file at run time - edits are picked up without touching the YAML. Preferred agent pattern for complex scripts: write_file(".reqly/collections/<name>/scripts/post.js", script) then set postScriptFile: "scripts/post.js". No ../path-traversal allowed.' },
          specOperationId: { type: 'string', description: 'OpenAPI operationId for contract validation, used when the collection has a spec configured (set_collection_spec) and the request URL does not cleanly map to a spec path. Get valid values from list_spec_operations.' }
        },
        required: ['id', 'name', 'method', 'url']
      }
    },
    required: ['collectionName', 'request']
  }
};

export async function handler(args: any, context: EngineContext): Promise<ToolHandlerResult> {
  try {
    await context.collectionManager.addRequest(args.collectionName, args.request);

    // For gRPC requests: attempt to auto-generate the message scaffold (T-166).
    // If proto loading fails we still return success - the scaffold is best-effort.
    let grpcMessageScaffold: Record<string, unknown> | undefined;
    const req = args.request;
    if (req.type === 'grpc' && req.grpc?.protoFile && req.grpc?.service && req.grpc?.method) {
      grpcMessageScaffold = await buildGrpcScaffold(
        req.grpc.protoFile,
        req.grpc.service,
        req.grpc.method,
        context.collectionManager.getBaseDir(),
      );
    }

    return {
      content: [{
        type: 'text',
        text: JSON.stringify({ success: true, ...(grpcMessageScaffold ? { grpcMessageScaffold } : {}) }),
      }],
    };
  } catch (e: any) {
    return { content: [{ type: 'text', text: e.message }], isError: true };
  }
}

/**
 * Attempts to load the proto file and extract the input message scaffold for
 * the given service/method. Returns undefined on any error (best-effort).
 */
async function buildGrpcScaffold(
  protoFile: string,
  service: string,
  method: string,
  baseDir: string,
): Promise<Record<string, unknown> | undefined> {
  try {
    const path = await import('path');
    // baseDir is `.reqly/collections` or similar; protos sit at `.reqly/protos/`
    const reqlyDir = path.default.dirname(baseDir);
    const protosDir = path.default.join(reqlyDir, 'protos');
    const protoPath = path.default.join(protosDir, protoFile);

    const grpcLoader = await import('@grpc/proto-loader');
    const packageDef = await grpcLoader.load(protoPath, {
      keepCase: true,
      longs: String,
      enums: String,
      defaults: true,
      oneofs: true,
      includeDirs: [protosDir],
    });

    const grpcJs = await import('@grpc/grpc-js');
    const pkgObj = grpcJs.loadPackageDefinition(packageDef) as any;

    // Navigate to the service constructor (e.g. "helloworld.Greeter")
    const parts = service.split('.');
    let svcDef: any = pkgObj;
    for (const p of parts) svcDef = svcDef?.[p];

    if (!svcDef?.service) return undefined;

    // Find the method descriptor
    const methodDef = svcDef.service.find((m: any) => m.originalName === method || m.path?.endsWith(`/${method}`));
    if (!methodDef?.requestType?.type?.field) return undefined;

    const { scaffoldMessage } = await import('../../engine/proto-scaffold.js');
    const fields = extractFields(methodDef.requestType.type.field);
    return scaffoldMessage(fields);
  } catch {
    return undefined;
  }
}

function extractFields(protoFields: any[]): import('../../engine/proto-scaffold.js').ProtoField[] {
  return protoFields.map((f: any) => {
    const isRepeated = f.label === 3; // LABEL_REPEATED = 3
    const typeName = f.typeName?.replace(/^\./, '');
    if (f.type === 11 /* TYPE_MESSAGE */ || f.type === 14 /* TYPE_ENUM */) {
      if (f.type === 14) return { name: f.name, type: 'enum', repeated: isRepeated };
      return {
        name: f.name,
        type: 'message',
        typeName,
        repeated: isRepeated,
        fields: f.messageType?.field ? extractFields(f.messageType.field) : [],
      };
    }
    const typeMap: Record<number, string> = {
      1: 'double', 2: 'float', 3: 'int64', 4: 'uint64', 5: 'int32',
      6: 'fixed64', 7: 'fixed32', 8: 'bool', 9: 'string', 12: 'bytes',
      13: 'uint32', 15: 'sfixed32', 16: 'sfixed64', 17: 'sint32', 18: 'sint64',
    };
    return { name: f.name, type: typeMap[f.type] ?? 'string', repeated: isRepeated };
  });
}

